### ISSUE TITLE
Error in reproducing the results

### ISSUE THREAD

**Issue by MrPeterJin** [helme/ecg_ptbxl_benchmarking#17]
I have followed the instructions of this page to reproduce the results. The file runs smoothly at first but throws error below:

(normal running code is omitted)

```python
model: fastai_inception1d
aggregating predictions...                                                                                                           
model: fastai_inception1d
aggregating predictions...                                                                                                           
model: fastai_inception1d
aggregating predictions...                                                                                                           
2022-01-25 13:27:06.109375: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-25 13:27:06.137879: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2899885000 Hz
2022-01-25 13:27:06.138434: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55bafb1f5e60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-01-25 13:27:06.138454: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Epoch 1/30
126/137 [==========================>...] - ETA: 0s - loss: 0.2361
Epoch 00001: val_loss improved from inf to 0.11070, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 2ms/step - loss: 0.2278 - val_loss: 0.1107
Epoch 2/30
125/137 [==========================>...] - ETA: 0s - loss: 0.1121
Epoch 00002: val_loss improved from 0.11070 to 0.09673, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.1113 - val_loss: 0.0967
Epoch 3/30
129/137 [===========================>..] - ETA: 0s - loss: 0.0995
Epoch 00003: val_loss improved from 0.09673 to 0.09149, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0992 - val_loss: 0.0915
Epoch 4/30
129/137 [===========================>..] - ETA: 0s - loss: 0.0925
Epoch 00004: val_loss improved from 0.09149 to 0.08855, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0923 - val_loss: 0.0886
Epoch 5/30
129/137 [===========================>..] - ETA: 0s - loss: 0.0881
Epoch 00005: val_loss improved from 0.08855 to 0.08636, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0881 - val_loss: 0.0864
Epoch 6/30
129/137 [===========================>..] - ETA: 0s - loss: 0.0849
Epoch 00006: val_loss improved from 0.08636 to 0.08473, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0847 - val_loss: 0.0847
Epoch 7/30
125/137 [==========================>...] - ETA: 0s - loss: 0.0822
Epoch 00007: val_loss improved from 0.08473 to 0.08354, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0820 - val_loss: 0.0835
Epoch 8/30
129/137 [===========================>..] - ETA: 0s - loss: 0.0803
Epoch 00008: val_loss improved from 0.08354 to 0.08275, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0803 - val_loss: 0.0828
Epoch 9/30
130/137 [===========================>..] - ETA: 0s - loss: 0.0782
Epoch 00009: val_loss improved from 0.08275 to 0.08182, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0782 - val_loss: 0.0818
Epoch 10/30
130/137 [===========================>..] - ETA: 0s - loss: 0.0767
Epoch 00010: val_loss improved from 0.08182 to 0.08148, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0768 - val_loss: 0.0815
Epoch 11/30
131/137 [===========================>..] - ETA: 0s - loss: 0.0754
Epoch 00011: val_loss improved from 0.08148 to 0.08059, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0754 - val_loss: 0.0806
Epoch 12/30
128/137 [===========================>..] - ETA: 0s - loss: 0.0742
Epoch 00012: val_loss improved from 0.08059 to 0.08009, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0743 - val_loss: 0.0801
Epoch 13/30
129/137 [===========================>..] - ETA: 0s - loss: 0.0734
Epoch 00013: val_loss improved from 0.08009 to 0.07966, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0733 - val_loss: 0.0797
Epoch 14/30
127/137 [==========================>...] - ETA: 0s - loss: 0.0723
Epoch 00014: val_loss improved from 0.07966 to 0.07932, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0724 - val_loss: 0.0793
Epoch 15/30
129/137 [===========================>..] - ETA: 0s - loss: 0.0717
Epoch 00015: val_loss improved from 0.07932 to 0.07899, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0716 - val_loss: 0.0790
Epoch 16/30
130/137 [===========================>..] - ETA: 0s - loss: 0.0706
Epoch 00016: val_loss improved from 0.07899 to 0.07862, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0706 - val_loss: 0.0786
Epoch 17/30
124/137 [==========================>...] - ETA: 0s - loss: 0.0701
Epoch 00017: val_loss improved from 0.07862 to 0.07860, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0699 - val_loss: 0.0786
Epoch 18/30
128/137 [===========================>..] - ETA: 0s - loss: 0.0693
Epoch 00018: val_loss improved from 0.07860 to 0.07816, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0694 - val_loss: 0.0782
Epoch 19/30
131/137 [===========================>..] - ETA: 0s - loss: 0.0687
Epoch 00019: val_loss did not improve from 0.07816
137/137 [==============================] - 0s 1ms/step - loss: 0.0688 - val_loss: 0.0782
Epoch 20/30
131/137 [===========================>..] - ETA: 0s - loss: 0.0683
Epoch 00020: val_loss improved from 0.07816 to 0.07803, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0683 - val_loss: 0.0780
Epoch 21/30
128/137 [===========================>..] - ETA: 0s - loss: 0.0676
Epoch 00021: val_loss improved from 0.07803 to 0.07780, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0676 - val_loss: 0.0778
Epoch 22/30
128/137 [===========================>..] - ETA: 0s - loss: 0.0670
Epoch 00022: val_loss did not improve from 0.07780
137/137 [==============================] - 0s 1ms/step - loss: 0.0672 - val_loss: 0.0779
Epoch 23/30
129/137 [===========================>..] - ETA: 0s - loss: 0.0669
Epoch 00023: val_loss improved from 0.07780 to 0.07774, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0668 - val_loss: 0.0777
Epoch 24/30
128/137 [===========================>..] - ETA: 0s - loss: 0.0663
Epoch 00024: val_loss improved from 0.07774 to 0.07758, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0664 - val_loss: 0.0776
Epoch 25/30
131/137 [===========================>..] - ETA: 0s - loss: 0.0659
Epoch 00025: val_loss improved from 0.07758 to 0.07726, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0660 - val_loss: 0.0773
Epoch 26/30
127/137 [==========================>...] - ETA: 0s - loss: 0.0656
Epoch 00026: val_loss did not improve from 0.07726
137/137 [==============================] - 0s 1ms/step - loss: 0.0654 - val_loss: 0.0773
Epoch 27/30
128/137 [===========================>..] - ETA: 0s - loss: 0.0652
Epoch 00027: val_loss did not improve from 0.07726
137/137 [==============================] - 0s 1ms/step - loss: 0.0652 - val_loss: 0.0773
Epoch 28/30
131/137 [===========================>..] - ETA: 0s - loss: 0.0648
Epoch 00028: val_loss improved from 0.07726 to 0.07723, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0647 - val_loss: 0.0772
Epoch 29/30
125/137 [==========================>...] - ETA: 0s - loss: 0.0645
Epoch 00029: val_loss improved from 0.07723 to 0.07714, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0645 - val_loss: 0.0771
Epoch 30/30
129/137 [===========================>..] - ETA: 0s - loss: 0.0641
Epoch 00030: val_loss improved from 0.07714 to 0.07690, saving model to ../output/exp0/models/Wavelet+NN/best_loss_model.h5
137/137 [==============================] - 0s 1ms/step - loss: 0.0640 - val_loss: 0.0769
Traceback (most recent call last):
  File "reproduce_results.py", line 59, in <module>
    main()
  File "reproduce_results.py", line 40, in main
    e.perform()
  File "/home/office-401-1/Downloads/ecg_ptbxl_benchmarking/code/experiments/scp_experiment.py", line 114, in perform
    model.predict(self.X_train).dump(mpath+'y_train_pred.npy')
  File "/home/office-401-1/Downloads/ecg_ptbxl_benchmarking/code/models/wavelet.py", line 158, in predict
    model = load_model(self.outputfolder+'best_loss_model.h5')#'best_score_model.h5', custom_objects={'keras_macro_auroc': keras_macro_auroc})
  File "/home/office-401-1/Documents/Anaconda3/envs/ecg_env/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/office-401-1/Documents/Anaconda3/envs/ecg_env/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 176, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

Can someone help me?

**Comment by MrPeterJin** [comment]
Hi,
I've found that it is the problem with the `h5py` package. While it reads the `.h5` checkpoints, higher than `2.10` version would throw out this error.  Sorry for the issues, my bad.
