### ISSUE TITLE
Error loading/dumping data with sampling frequency 500: File too large

### ISSUE THREAD

**Issue by rsaite** [helme/ecg_ptbxl_benchmarking#7]
When initializing the `SCPExperiment` with `sampling_frequency=500`, I observe the following error:

```
$ time python reproduce_results.py

Traceback (most recent call last):
  File "reproduce_results.py", line 64, in <module>
    main()
  File "reproduce_results.py", line 43, in main
    e.prepare()
  File "/home/rsaite/medalcare/ecg_ptbxl_benchmarking/code/experiments/scp_experiment.py", line 57, in prepare
    self.datafolder, self.sampling_frequency
  File "/home/rsaite/medalcare/ecg_ptbxl_benchmarking/code/utils/utils.py", line 151, in load_dataset
    X = load_raw_data_ptbxl(Y, sampling_rate, path)
  File "/home/rsaite/medalcare/ecg_ptbxl_benchmarking/code/utils/utils.py", line 196, in load_raw_data_ptbxl
    data.dump(path + "raw500.npy")
  File "/home/rsaite/anaconda3/envs/ecg_ptbxl/lib/python3.7/site-packages/numpy/core/_methods.py", line 241, in _dump
    pickle.dump(self, f, protocol=protocol)
OverflowError: cannot serialize a string larger than 4GiB
```

**Comment by helme** [comment]
Hi @rsaite,

thank you very much for pointing this out. Unfortunately I forgot to test for 500 Hz (since we mainly use 100 Hz), please excuse :)

According to [here](https://docs.python.org/3/library/pickle.html) `data.dump(path+'raw500.npy')` calls pickle with a protocol too low. I commited a fixed version [here](https://github.com/helme/ecg_ptbxl_benchmarking/commit/847517a03bd356f58889f0fdac05278f936603f8) where I replaced the calls with the following:

`pickle.dump(data, open(path+'raw500.npy', 'wb'), protocol=4)`

 I hope this resolves this issue for you. Before calling the script again, please be sure to delete again `data/ptbxl/raw500.npy` consisting of 0 bytes.

**Comment by helme** [comment]
And in case you want to save space while dumping, please see [this issue here](https://github.com/helme/ecg_ptbxl_benchmarking/issues/8#issuecomment-744365381) where I described a way to dump PTB-XL as 16bit signed integers.
